dietpi_image_url            = "https://dietpi.com/downloads/images/DietPi_RPi234-ARMv8-Trixie.img.xz"
dietpi_image_checksum       = "8e77cf05ce5d36b53cd989ce697645ecf4a4a8fdda1e38dcfadaab48044d9655"
dietpi_image_path           = "DietPi_RPi234-ARMv8-Trixie.img"
dietpi_locale               = "en_GB.UTF-8"
dietpi_keyboard_layout      = "us"
dietpi_timezone             = "Europe/London"
dietpi_ethernet_enabled     = "0"
dietpi_wifi_enabled         = "1"
dietpi_wifi_country_code    = "GB"
dietpi_hostname             = "vox"
dietpi_setup_automated      = "1"
dietpi_enable_ipv6          = "0"
dietpi_disable_ssh_password = "1"

